version: "3.8"
services:
  roscore:
    image: ros:noetic-ros-core
    command: /bin/bash -c "roscore"
    networks:
      ros_network:
        ipv4_address: 172.28.1.2

  rust-builder:
    build: .
    command: /bin/bash
    privileged: true
    tty: true
    volumes:
      - ./:/home/proj
    networks:
      ros_network:
        ipv4_address: 172.28.1.3
    environment:
      - ROS_MASTER_URI=http://172.28.1.2:11311
      - ROS_IP=172.28.1.3

networks:
  ros_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
