[package]
name = "ros-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9.11"
rosrust_msg = "0.1.7"

[[bin]]
name = "publisher"
path = "src/drive_pub.rs"

[[bin]]
name = "subscriber"
path = "src/drive_sub.rs"
