# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/base/mz7020_som_base.xdc

# XDC: imports/base/bitstream_compression_enable.xdc

# Block Designs: bd/mz7020_som_base/mz7020_som_base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base || ORIG_REF_NAME==mz7020_som_base} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_ps7_0/mz7020_som_base_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_ps7_0 || ORIG_REF_NAME==mz7020_som_base_ps7_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_ps7_axi_periph_0/mz7020_som_base_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_ps7_axi_periph_0 || ORIG_REF_NAME==mz7020_som_base_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_xlconcat_0_0/mz7020_som_base_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_xlconcat_0_0 || ORIG_REF_NAME==mz7020_som_base_xlconcat_0_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_axi_intc_0_0/mz7020_som_base_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_axi_intc_0_0 || ORIG_REF_NAME==mz7020_som_base_axi_intc_0_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_xlconstant_0_0/mz7020_som_base_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_xlconstant_0_0 || ORIG_REF_NAME==mz7020_som_base_xlconstant_0_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_100MHz_0/mz7020_som_base_proc_sys_reset_100MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_100MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_100MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_142MHz_0/mz7020_som_base_proc_sys_reset_142MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_142MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_142MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_166MHz_0/mz7020_som_base_proc_sys_reset_166MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_166MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_166MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_200MHz_0/mz7020_som_base_proc_sys_reset_200MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_200MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_200MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_41MHz_0/mz7020_som_base_proc_sys_reset_41MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_41MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_41MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_proc_sys_reset_50MHz_0/mz7020_som_base_proc_sys_reset_50MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_proc_sys_reset_50MHz_0 || ORIG_REF_NAME==mz7020_som_base_proc_sys_reset_50MHz_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_clk_wiz_0_0/mz7020_som_base_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_clk_wiz_0_0 || ORIG_REF_NAME==mz7020_som_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mz7020_som_base/ip/mz7020_som_base_auto_pc_0/mz7020_som_base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mz7020_som_base_auto_pc_0 || ORIG_REF_NAME==mz7020_som_base_auto_pc_0} -quiet] -quiet

# XDC: /work/git/avnet/hdl/projects/mz7020_som_base_2023_1/mz7020_som_base.gen/sources_1/bd/mz7020_som_base/mz7020_som_base_ooc.xdc
